---
- name: Kubernetes Cluster Setup
  hosts: localhost  # This includes both master and worker nodes

  tasks:
    - name: network config
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
    # Enable IPv4 forwarding and load required modules
    - name: Enable IPv4 forwarding and modules
      command: |
        sudo modprobe overlay
        sudo modprobe br_netfilter
        echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
        echo 1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
        echo 1 > /proc/sys/net/ipv4/ip_forward

    # Update package lists
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes 

    # Install required dependencies
    - name: Install dependencies
      shell: |
        sudo apt-get update
        sudo apt-get install ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg

    - name: Add containerd repository
      shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          
     # Update package lists
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes 

    # Install and configure containerd
    - name: Install containerd
      apt:
        name: containerd.io
        state: present
      become: yes

    - name: Start and enable containerd service
      systemd:
        name: containerd
        state: started
        enabled: yes
      become: yes

    - name: Configure containerd
      copy:
        content: |
          version = 2
          [plugins]
            [plugins."io.containerd.grpc.v1.cri"]
              [plugins."io.containerd.grpc.v1.cri".containerd]
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
                  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                    runtime_type = "io.containerd.runc.v2"
                    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                      SystemdCgroup = true
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: 0644

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted
      become: yes

    # Install Kubernetes components
    - name: Update apt cache again
      apt:
        update_cache: yes
      become: yes

    - name: Create keyring directory if not exists
      file:
        path: /etc/apt/keyrings
        state: directory
      become: yes

    - name: Add Kubernetes GPG key
      shell: sudo apt-get install -y apt-transport-https ca-certificates curl gpg

    - name: Download the public signing key for the Kubernetes package repositories
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add the appropriate Kubernetes apt repository
      command: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list


    - name: Update apt cache again
      apt:
        update_cache: yes
      become: yes

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present